import { Injectable } from '@angular/core';
import { Property } from './shared/property.model';

@Injectable({
    providedIn: 'root'
})

export class PropertiesService {
    private properties: Property[] = [
        new Property([{ long_name: '102', short_name: '102', types: [] },
        { long_name: 'Nicholson Street', short_name: 'Nicholson St', types: [] },
        { long_name: 'Abbotsford', short_name: 'Abbotsford', types: [] },
        { long_name: 'City of Yarra', short_name: 'Yarra', types: [] },
        { long_name: 'Victoria', short_name: 'VIC', types: [] },
        { long_name: 'Australia', short_name: 'AU', types: [] },
        { long_name: '3067', short_name: '3067', types: [] }
        ],
            true,
            true,
            true,
            'https://cdn.pixabay.com/photo/2016/11/29/03/53/architecture-1867187_960_720.jpg',
            'https://cdn.pixabay.com/photo/2017/04/10/22/28/residence-2219972_960_720.jpg',
            '',
            '',
            '',
            true,
            true,
            true,
            'Lux house near the seashore',
            '2',
            true,
            true,
            10,
            '5',
            'hotel',
            true,
            true
        ),
        new Property([{ long_name: '102', short_name: '102', types: [] },
        { long_name: 'Nicholson Street', short_name: 'Nicholson St', types: [] },
        { long_name: 'Abbotsford', short_name: 'Abbotsford', types: [] },
        { long_name: 'City of Yarra', short_name: 'Yarra', types: [] },
        { long_name: 'Victoria', short_name: 'VIC', types: [] },
        { long_name: 'Australia', short_name: 'AU', types: [] },
        { long_name: '3067', short_name: '3067', types: [] }
        ],
            true,
            true,
            true,
            'https://cdn.pixabay.com/photo/2017/04/10/22/28/residence-2219972_960_720.jpg',
            'https://cdn.pixabay.com/photo/2017/04/10/22/28/residence-2219972_960_720.jpg',
            '',
            '',
            '',
            true,
            true,
            true,
            'Modern villa with alll amenities',
            '2',
            true,
            true,
            10,
            '5',
            'hotel',
            true,
            true
        ),
        new Property([{ long_name: '102', short_name: '102', types: [] },
        { long_name: 'Nicholson Street', short_name: 'Nicholson St', types: [] },
        { long_name: 'Abbotsford', short_name: 'Abbotsford', types: [] },
        { long_name: 'City of Yarra', short_name: 'Yarra', types: [] },
        { long_name: 'Victoria', short_name: 'VIC', types: [] },
        { long_name: 'Australia', short_name: 'AU', types: [] },
        { long_name: '3067', short_name: '3067', types: [] }
        ],
            true,
            true,
            true,
            'https://cdn.pixabay.com/photo/2018/03/18/15/26/villa-3237114_960_720.jpg',
            'https://cdn.pixabay.com/photo/2017/04/10/22/28/residence-2219972_960_720.jpg',
            '',
            '',
            '',
            true,
            true,
            true,
            'Big house',
            '2',
            true,
            true,
            10,
            '5',
            'hotel',
            true,
            true
        ),
        new Property([{ long_name: '102', short_name: '102', types: [] },
        { long_name: 'Nicholson Street', short_name: 'Nicholson St', types: [] },
        { long_name: 'Abbotsford', short_name: 'Abbotsford', types: [] },
        { long_name: 'City of Yarra', short_name: 'Yarra', types: [] },
        { long_name: 'Victoria', short_name: 'VIC', types: [] },
        { long_name: 'Australia', short_name: 'AU', types: [] },
        { long_name: '3067', short_name: '3067', types: [] }
        ],
            true,
            true,
            true,
            'https://cdn.pixabay.com/photo/2019/08/17/09/37/lost-places-4411813_960_720.jpg',
            'https://cdn.pixabay.com/photo/2017/04/10/22/28/residence-2219972_960_720.jpg',
            '',
            '',
            '',
            true,
            true,
            true,
            'Big house',
            '2',
            true,
            true,
            10,
            '5',
            'hotel',
            true,
            true
        ),
        new Property([{ long_name: '102', short_name: '102', types: [] },
        { long_name: 'Nicholson Street', short_name: 'Nicholson St', types: [] },
        { long_name: 'Abbotsford', short_name: 'Abbotsford', types: [] },
        { long_name: 'City of Yarra', short_name: 'Yarra', types: [] },
        { long_name: 'Victoria', short_name: 'VIC', types: [] },
        { long_name: 'Australia', short_name: 'AU', types: [] },
        { long_name: '3067', short_name: '3067', types: [] }
        ],
            true,
            true,
            true,
            'https://cdn.pixabay.com/photo/2015/11/06/11/39/single-family-home-1026368_960_720.jpg',
            'https://cdn.pixabay.com/photo/2017/04/10/22/28/residence-2219972_960_720.jpg',
            '',
            '',
            '',
            true,
            true,
            true,
            'Big house',
            '2',
            true,
            true,
            10,
            '5',
            'hotel',
            true,
            true
        ),
        new Property([{ long_name: '102', short_name: '102', types: [] },
        { long_name: 'Nicholson Street', short_name: 'Nicholson St', types: [] },
        { long_name: 'Abbotsford', short_name: 'Abbotsford', types: [] },
        { long_name: 'City of Yarra', short_name: 'Yarra', types: [] },
        { long_name: 'Victoria', short_name: 'VIC', types: [] },
        { long_name: 'Australia', short_name: 'AU', types: [] },
        { long_name: '3067', short_name: '3067', types: [] }
        ],
            true,
            true,
            true,
            'https://assets.architecturaldesigns.com/plan_assets/324992268/large/23703JD_01_1553616680.jpg?1553616681.jpg',
            'https://cdn.pixabay.com/photo/2017/04/10/22/28/residence-2219972_960_720.jpg',
            '',
            '',
            '',
            true,
            true,
            true,
            'Big house',
            '2',
            true,
            true,
            10,
            '5',
            'hotel',
            true,
            true
        ),
        new Property([{ long_name: '102', short_name: '102', types: [] },
        { long_name: 'Nicholson Street', short_name: 'Nicholson St', types: [] },
        { long_name: 'Abbotsford', short_name: 'Abbotsford', types: [] },
        { long_name: 'City of Yarra', short_name: 'Yarra', types: [] },
        { long_name: 'Victoria', short_name: 'VIC', types: [] },
        { long_name: 'Australia', short_name: 'AU', types: [] },
        { long_name: '3067', short_name: '3067', types: [] }
        ],
            true,
            true,
            true,
            'https://cdn.pixabay.com/photo/2015/11/06/11/39/single-family-home-1026368_960_720.jpg',
            'https://cdn.pixabay.com/photo/2017/04/10/22/28/residence-2219972_960_720.jpg',
            '',
            '',
            '',
            true,
            true,
            true,
            'Big house',
            '2',
            true,
            true,
            10,
            '5',
            'hotel',
            true,
            true
        ),
        new Property([{ long_name: '102', short_name: '102', types: [] },
        { long_name: 'Nicholson Street', short_name: 'Nicholson St', types: [] },
        { long_name: 'Abbotsford', short_name: 'Abbotsford', types: [] },
        { long_name: 'City of Yarra', short_name: 'Yarra', types: [] },
        { long_name: 'Victoria', short_name: 'VIC', types: [] },
        { long_name: 'Australia', short_name: 'AU', types: [] },
        { long_name: '3067', short_name: '3067', types: [] }
        ],
            true,
            true,
            true,
            'https://cdn.pixabay.com/photo/2015/11/06/11/39/single-family-home-1026368_960_720.jpg',
            'https://cdn.pixabay.com/photo/2017/04/10/22/28/residence-2219972_960_720.jpg',
            '',
            '',
            '',
            true,
            true,
            true,
            'Big house',
            '2',
            true,
            true,
            10,
            '5',
            'hotel',
            true,
            true
        ),
        new Property([{ long_name: '102', short_name: '102', types: [] },
        { long_name: 'Nicholson Street', short_name: 'Nicholson St', types: [] },
        { long_name: 'Abbotsford', short_name: 'Abbotsford', types: [] },
        { long_name: 'City of Yarra', short_name: 'Yarra', types: [] },
        { long_name: 'Victoria', short_name: 'VIC', types: [] },
        { long_name: 'Australia', short_name: 'AU', types: [] },
        { long_name: '3067', short_name: '3067', types: [] }
        ],
            true,
            true,
            true,
            'https://img.newatlas.com/iron-maiden-house-11.jpg?auto=format%2Ccompress&fit=max&q=60&w=1000&s=fde486fc78f62edd9a9cfef9a90499ff.jpg',
            'https://cdn.pixabay.com/photo/2017/04/10/22/28/residence-2219972_960_720.jpg',
            '',
            '',
            '',
            true,
            true,
            true,
            'Big house',
            '2',
            true,
            true,
            10,
            '5',
            'hotel',
            true,
            true
        ),
        new Property([{ long_name: '102', short_name: '102', types: [] },
        { long_name: 'Nicholson Street', short_name: 'Nicholson St', types: [] },
        { long_name: 'Abbotsford', short_name: 'Abbotsford', types: [] },
        { long_name: 'City of Yarra', short_name: 'Yarra', types: [] },
        { long_name: 'Victoria', short_name: 'VIC', types: [] },
        { long_name: 'Australia', short_name: 'AU', types: [] },
        { long_name: '3067', short_name: '3067', types: [] }
        ],
            true,
            true,
            true,
            'https://www.incimages.com/uploaded_files/image/970x450/getty_856794670_385651.jpg',
            'https://cdn.pixabay.com/photo/2017/04/10/22/28/residence-2219972_960_720.jpg',
            '',
            '',
            '',
            true,
            true,
            true,
            'Big house',
            '2',
            true,
            true,
            10,
            '5',
            'hotel',
            true,
            true
        ),
        new Property([{ long_name: '102', short_name: '102', types: [] },
        { long_name: 'Nicholson Street', short_name: 'Nicholson St', types: [] },
        { long_name: 'Abbotsford', short_name: 'Abbotsford', types: [] },
        { long_name: 'City of Yarra', short_name: 'Yarra', types: [] },
        { long_name: 'Victoria', short_name: 'VIC', types: [] },
        { long_name: 'Australia', short_name: 'AU', types: [] },
        { long_name: '3067', short_name: '3067', types: [] }
        ],
            true,
            true,
            true,
            'https://amp.businessinsider.com/images/5bdc87448c35ab6a120935eb-1536-1152.jpg',
            'https://cdn.pixabay.com/photo/2017/04/10/22/28/residence-2219972_960_720.jpg',
            '',
            '',
            '',
            true,
            true,
            true,
            'Big house',
            '2',
            true,
            true,
            10,
            '5',
            'hotel',
            true,
            true
        )
    ];

    getProperties() {
        return this.properties.slice();
    }
}
